# PHP
*PHP-8.5=https://windows.php.net/downloads/releases/archives/php-8.5.0-nts-Win32-vs17-x64.zip
*PHP-8.4=https://windows.php.net/downloads/releases/archives/php-8.4.12-nts-Win32-vs17-x64.zip
*PHP-8.3=https://windows.php.net/downloads/releases/archives/php-8.3.28-nts-Win32-vs16-x64.zip
*PHP-8.2=https://windows.php.net/downloads/releases/archives/php-8.2.28-nts-Win32-vs16-x64.zip
*PHP-8.1=https://windows.php.net/downloads/releases/archives/php-8.1.32-nts-Win32-vs16-x64.zip
*PHP-7.4=https://windows.php.net/downloads/releases/archives/php-7.4.9-nts-Win32-vc15-x64.zip
*PHP-7.3=https://windows.php.net/downloads/releases/archives/php-7.3.9-nts-Win32-VC15-x64.zip
*PHP-7.2=https://windows.php.net/downloads/releases/archives/php-7.2.9-nts-Win32-VC15-x64.zip
*PHP-7.1=https://windows.php.net/downloads/releases/archives/php-7.1.9-nts-Win32-VC14-x64.zip
*PHP-5.6=https://windows.php.net/downloads/releases/archives/php-5.6.40-nts-Win32-VC11-x64.zip

# Servidores Web
*Apache-2.4.66=https://www.apachelounge.com/download/VS18/binaries/httpd-2.4.66-260107-Win64-VS18.zip
Apache-2.4.65=https://www.apachelounge.com/download/VS17/binaries/httpd-2.4.65-250724-Win64-VS17.zip
Apache-2.4.57=https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.57-win64-VS16.zip
Nginx-1.29.4=https://nginx.org/download/nginx-1.29.4.zip

# Node.js
node-25.2=https://nodejs.org/dist/v25.2.1/node-v25.2.1-win-x64.zip
node-24.12=https://nodejs.org/dist/v24.12.0/node-v24.12.0-win-x64.zip
node-22.21=https://nodejs.org/dist/v22.21.1/node-v22.21.1-win-x64.zip

# Ferramentas de banco de dados
DBeaver=https://dbeaver.io/files/dbeaver-ce-latest-win32.win32.x86_64.zip
HeidiSQL=https://www.heidisql.com/downloads/releases/HeidiSQL_12.17_64_Portable.zip
phpMyAdmin-5.2.2=https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-english.zip
phpMyAdmin-6.0snapshot=https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-english.tar.xz
phpPgAdmin=https://github.com/phppgadmin/phppgadmin/releases/download/REL_7-13-0/phpPgAdmin-7.13.0.zip
Adminer=https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php

# Ferramentas locais
Cmder=https://github.com/cmderdev/cmder/releases/download/v1.3.25/cmder.zip
Notepad++=https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.6/npp.8.9.6.portable.x64.zip

# MySQL
*mysql-8.4=https://cdn.mysql.com/archives/mysql-8.4/mysql-8.4.6-winx64.zip
mysql-8.0=https://cdn.mysql.com/archives/mysql-8.0/mysql-8.0.40-winx64.zip
mysql-5.7=https://cdn.mysql.com/archives/mysql-5.7/mysql-5.7.39-winx64.zip

# MariaDB
mariadb-11.4=https://archive.mariadb.org/mariadb-11.4.2/winx64-packages/mariadb-11.4.2-winx64.zip
mariadb-10.11=https://archive.mariadb.org/mariadb-10.11.8/winx64-packages/mariadb-10.11.8-winx64.zip

# PostgreSQL
postgresql-18.0=https://sbp.enterprisedb.com/getfile.jsp?fileid=1259741
postgresql-17.2=https://sbp.enterprisedb.com/getfile.jsp?fileid=1259294
postgresql-16.6=https://sbp.enterprisedb.com/getfile.jsp?fileid=1259297
postgresql-15.10=https://sbp.enterprisedb.com/getfile.jsp?fileid=1259300

# MongoDB
mongodb-8=https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-8.0.4.zip
mongodb-7=https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-7.0.14.zip

# Redis
redis-7.0=https://github.com/tporadowski/redis/releases/download/v5.0.14.1/Redis-x64-5.0.14.1.zip

# Memcached
memcached-1.6=https://github.com/nono303/memcached/releases/download/v1.6.22/memcached-1.6.22-win64.zip
