# Sites
Blank|framework=Blank|version=Padrão|php>=5.6=
PHP|framework=PHP|version=Padrão|php>=5.6=inline:php

# Frameworks
Laravel 12|framework=Laravel|version=12.x|php>=8.2=composer create-project laravel/laravel:^12.0 {name}
Laravel 11|framework=Laravel|version=11.x|php>=8.2=composer create-project laravel/laravel:^11.0 {name}
Laravel 10|framework=Laravel|version=10.x|php>=8.1=composer create-project laravel/laravel:^10.0 {name}
Symfony 7.3|framework=Symfony|version=7.3|php>=8.2=composer create-project symfony/skeleton:^7.3 {name}
Symfony 6.4 LTS|framework=Symfony|version=6.4 LTS|php>=8.1=composer create-project symfony/skeleton:^6.4 {name}
CakePHP 5.2|framework=CakePHP|version=5.2|php>=8.1=composer create-project cakephp/app:^5.2 {name}
CakePHP 5.1|framework=CakePHP|version=5.1|php>=8.1=composer create-project cakephp/app:^5.1 {name}
CakePHP 5.0|framework=CakePHP|version=5.0|php>=8.1=composer create-project cakephp/app:^5.0 {name}
CakePHP 4.6|framework=CakePHP|version=4.6|php>=7.4=composer create-project cakephp/app:^4.6 {name}
CakePHP 4.5|framework=CakePHP|version=4.5|php>=7.4=composer create-project cakephp/app:^4.5 {name}
CakePHP 3.10|framework=CakePHP|version=3.10|php>=5.6|php<8.0=composer create-project cakephp/app:^3.10 {name}

# CMS
WordPress 6.8|framework=WordPress|version=6.8|php>=7.2=https://wordpress.org/latest.zip
